CONTIKI_PROJECT = base-station mobile-robot sensor-node

all: $(CONTIKI_PROJECT)

# Path to Contiki-NG
CONTIKI = /home/uttammahata/storage/contiki-ng

# Add math library for calculations
TARGET_LIBFILES += -lm

# Add project source files

# Include the Contiki-NG build system
include $(CONTIKI)/Makefile.include
