#ifndef PROJECT_CONF_H
#define PROJECT_CONF_H

/* Enable logging */
#define LOG_CONF_LEVEL_MAIN LOG_LEVEL_INFO

/* Network configuration */
#define NETSTACK_CONF_WITH_IPV6 1
#define UIP_CONF_ROUTER 1

/* Energy monitoring */
#define ENERGEST_CONF_ON 1

/* WSN Deployment specific configurations */
#define WSN_DEPLOYMENT_CONF_MAX_SENSORS 100
#define WSN_DEPLOYMENT_CONF_MAX_ROBOTS 2
#define WSN_DEPLOYMENT_CONF_MAX_LOCATION_AREAS 20
#define WSN_DEPLOYMENT_CONF_MAX_GRIDS_PER_LA 16
#define WSN_DEPLOYMENT_CONF_ROBOT_CAPACITY 15
#define WSN_DEPLOYMENT_CONF_INITIAL_STOCK 10

/* Network parameters */
#define WSN_DEPLOYMENT_CONF_SENSOR_RANGE 50    /* meters */
#define WSN_DEPLOYMENT_CONF_COMM_RANGE 100     /* meters */
#define WSN_DEPLOYMENT_CONF_ROBOT_PERCEPTION_RANGE 200 /* meters */

/* Node types */
#define WSN_NODE_TYPE_BASE_STATION 1
#define WSN_NODE_TYPE_MOBILE_ROBOT 2
#define WSN_NODE_TYPE_SENSOR 3

#endif /* PROJECT_CONF_H */
